apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: zqdb5zkqz-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-b61473885c.bvv2.p3.openshiftapps.com/rhtap/rhtap-qe:6ecf4920214ac26bc42933102c2903ec5a7d16b0@sha256:0ee7ec55c4404cab5db01dc2d51383700168dc3d1e54bd0fed17e286dc74bd2c
        name: container-image  
